#include <nan.h>
#include <linux/input.h>
#include <linux/uinput.h>

using namespace v8;
using namespace node;

#define QUOTE(name) name

namespace {

NAN_METHOD(InputEvent) {
    Nan::HandleScope scope;

    int type;
    int code;
    int value;

    assert(info.Length() == 3);
    type = info[0]->Int32Value();
    code = info[1]->Int32Value();
    value = info[2]->Int32Value();

    struct input_event ev;
    memset(&ev, 0, sizeof(ev));
    gettimeofday(&ev.time, NULL);
    ev.type = type;
    ev.code = code;
    ev.value = value;

    const char* ev_buf = reinterpret_cast<const char*>(
                             const_cast<const input_event*>(&ev));
    info.GetReturnValue().Set(
        Nan::CopyBuffer(ev_buf, sizeof(ev)).ToLocalChecked());
}

void Initialize(Local<Object> target) {
    /* input.h */
    target->Set(Nan::New("EV_SYN").ToLocalChecked(),
                Nan::New(EV_SYN));
    target->Set(Nan::New("EV_KEY").ToLocalChecked(),
                Nan::New(EV_KEY));
    target->Set(Nan::New("EV_REL").ToLocalChecked(),
                Nan::New(EV_REL));
    target->Set(Nan::New("EV_ABS").ToLocalChecked(),
                Nan::New(EV_ABS));
    target->Set(Nan::New("EV_MSC").ToLocalChecked(),
                Nan::New(EV_MSC));
    target->Set(Nan::New("EV_SW").ToLocalChecked(),
                Nan::New(EV_SW));
    target->Set(Nan::New("EV_LED").ToLocalChecked(),
                Nan::New(EV_LED));
    target->Set(Nan::New("EV_SND").ToLocalChecked(),
                Nan::New(EV_SND));
    target->Set(Nan::New("EV_REP").ToLocalChecked(),
                Nan::New(EV_REP));
    target->Set(Nan::New("EV_FF").ToLocalChecked(),
                Nan::New(EV_FF));
    target->Set(Nan::New("EV_PWR").ToLocalChecked(),
                Nan::New(EV_PWR));
    target->Set(Nan::New("EV_FF_STATUS").ToLocalChecked(),
                Nan::New(EV_FF_STATUS));
    target->Set(Nan::New("EV_MAX").ToLocalChecked(),
                Nan::New(EV_MAX));
    target->Set(Nan::New("EV_CNT").ToLocalChecked(),
                Nan::New(EV_CNT));
    target->Set(Nan::New("SYN_REPORT").ToLocalChecked(),
                Nan::New(SYN_REPORT));
    target->Set(Nan::New("SYN_CONFIG").ToLocalChecked(),
                Nan::New(SYN_CONFIG));
    target->Set(Nan::New("SYN_MT_REPORT").ToLocalChecked(),
                Nan::New(SYN_MT_REPORT));
    target->Set(Nan::New("SYN_DROPPED").ToLocalChecked(),
                Nan::New(SYN_DROPPED));
    target->Set(Nan::New("KEY_RESERVED").ToLocalChecked(),
                Nan::New(KEY_RESERVED));
    target->Set(Nan::New("KEY_ESC").ToLocalChecked(),
                Nan::New(KEY_ESC));
    target->Set(Nan::New("KEY_1").ToLocalChecked(),
                Nan::New(KEY_1));
    target->Set(Nan::New("KEY_2").ToLocalChecked(),
                Nan::New(KEY_2));
    target->Set(Nan::New("KEY_3").ToLocalChecked(),
                Nan::New(KEY_3));
    target->Set(Nan::New("KEY_4").ToLocalChecked(),
                Nan::New(KEY_4));
    target->Set(Nan::New("KEY_5").ToLocalChecked(),
                Nan::New(KEY_5));
    target->Set(Nan::New("KEY_6").ToLocalChecked(),
                Nan::New(KEY_6));
    target->Set(Nan::New("KEY_7").ToLocalChecked(),
                Nan::New(KEY_7));
    target->Set(Nan::New("KEY_8").ToLocalChecked(),
                Nan::New(KEY_8));
    target->Set(Nan::New("KEY_9").ToLocalChecked(),
                Nan::New(KEY_9));
    target->Set(Nan::New("KEY_0").ToLocalChecked(),
                Nan::New(KEY_0));
    target->Set(Nan::New("KEY_MINUS").ToLocalChecked(),
                Nan::New(KEY_MINUS));
    target->Set(Nan::New("KEY_EQUAL").ToLocalChecked(),
                Nan::New(KEY_EQUAL));
    target->Set(Nan::New("KEY_BACKSPACE").ToLocalChecked(),
                Nan::New(KEY_BACKSPACE));
    target->Set(Nan::New("KEY_TAB").ToLocalChecked(),
                Nan::New(KEY_TAB));
    target->Set(Nan::New("KEY_Q").ToLocalChecked(),
                Nan::New(KEY_Q));
    target->Set(Nan::New("KEY_W").ToLocalChecked(),
                Nan::New(KEY_W));
    target->Set(Nan::New("KEY_E").ToLocalChecked(),
                Nan::New(KEY_E));
    target->Set(Nan::New("KEY_R").ToLocalChecked(),
                Nan::New(KEY_R));
    target->Set(Nan::New("KEY_T").ToLocalChecked(),
                Nan::New(KEY_T));
    target->Set(Nan::New("KEY_Y").ToLocalChecked(),
                Nan::New(KEY_Y));
    target->Set(Nan::New("KEY_U").ToLocalChecked(),
                Nan::New(KEY_U));
    target->Set(Nan::New("KEY_I").ToLocalChecked(),
                Nan::New(KEY_I));
    target->Set(Nan::New("KEY_O").ToLocalChecked(),
                Nan::New(KEY_O));
    target->Set(Nan::New("KEY_P").ToLocalChecked(),
                Nan::New(KEY_P));
    target->Set(Nan::New("KEY_LEFTBRACE").ToLocalChecked(),
                Nan::New(KEY_LEFTBRACE));
    target->Set(Nan::New("KEY_RIGHTBRACE").ToLocalChecked(),
                Nan::New(KEY_RIGHTBRACE));
    target->Set(Nan::New("KEY_ENTER").ToLocalChecked(),
                Nan::New(KEY_ENTER));
    target->Set(Nan::New("KEY_LEFTCTRL").ToLocalChecked(),
                Nan::New(KEY_LEFTCTRL));
    target->Set(Nan::New("KEY_A").ToLocalChecked(),
                Nan::New(KEY_A));
    target->Set(Nan::New("KEY_S").ToLocalChecked(),
                Nan::New(KEY_S));
    target->Set(Nan::New("KEY_D").ToLocalChecked(),
                Nan::New(KEY_D));
    target->Set(Nan::New("KEY_F").ToLocalChecked(),
                Nan::New(KEY_F));
    target->Set(Nan::New("KEY_G").ToLocalChecked(),
                Nan::New(KEY_G));
    target->Set(Nan::New("KEY_H").ToLocalChecked(),
                Nan::New(KEY_H));
    target->Set(Nan::New("KEY_J").ToLocalChecked(),
                Nan::New(KEY_J));
    target->Set(Nan::New("KEY_K").ToLocalChecked(),
                Nan::New(KEY_K));
    target->Set(Nan::New("KEY_L").ToLocalChecked(),
                Nan::New(KEY_L));
    target->Set(Nan::New("KEY_SEMICOLON").ToLocalChecked(),
                Nan::New(KEY_SEMICOLON));
    target->Set(Nan::New("KEY_APOSTROPHE").ToLocalChecked(),
                Nan::New(KEY_APOSTROPHE));
    target->Set(Nan::New("KEY_GRAVE").ToLocalChecked(),
                Nan::New(KEY_GRAVE));
    target->Set(Nan::New("KEY_LEFTSHIFT").ToLocalChecked(),
                Nan::New(KEY_LEFTSHIFT));
    target->Set(Nan::New("KEY_BACKSLASH").ToLocalChecked(),
                Nan::New(KEY_BACKSLASH));
    target->Set(Nan::New("KEY_Z").ToLocalChecked(),
                Nan::New(KEY_Z));
    target->Set(Nan::New("KEY_X").ToLocalChecked(),
                Nan::New(KEY_X));
    target->Set(Nan::New("KEY_C").ToLocalChecked(),
                Nan::New(KEY_C));
    target->Set(Nan::New("KEY_V").ToLocalChecked(),
                Nan::New(KEY_V));
    target->Set(Nan::New("KEY_B").ToLocalChecked(),
                Nan::New(KEY_B));
    target->Set(Nan::New("KEY_N").ToLocalChecked(),
                Nan::New(KEY_N));
    target->Set(Nan::New("KEY_M").ToLocalChecked(),
                Nan::New(KEY_M));
    target->Set(Nan::New("KEY_COMMA").ToLocalChecked(),
                Nan::New(KEY_COMMA));
    target->Set(Nan::New("KEY_DOT").ToLocalChecked(),
                Nan::New(KEY_DOT));
    target->Set(Nan::New("KEY_SLASH").ToLocalChecked(),
                Nan::New(KEY_SLASH));
    target->Set(Nan::New("KEY_RIGHTSHIFT").ToLocalChecked(),
                Nan::New(KEY_RIGHTSHIFT));
    target->Set(Nan::New("KEY_KPASTERISK").ToLocalChecked(),
                Nan::New(KEY_KPASTERISK));
    target->Set(Nan::New("KEY_LEFTALT").ToLocalChecked(),
                Nan::New(KEY_LEFTALT));
    target->Set(Nan::New("KEY_SPACE").ToLocalChecked(),
                Nan::New(KEY_SPACE));
    target->Set(Nan::New("KEY_CAPSLOCK").ToLocalChecked(),
                Nan::New(KEY_CAPSLOCK));
    target->Set(Nan::New("KEY_F1").ToLocalChecked(),
                Nan::New(KEY_F1));
    target->Set(Nan::New("KEY_F2").ToLocalChecked(),
                Nan::New(KEY_F2));
    target->Set(Nan::New("KEY_F3").ToLocalChecked(),
                Nan::New(KEY_F3));
    target->Set(Nan::New("KEY_F4").ToLocalChecked(),
                Nan::New(KEY_F4));
    target->Set(Nan::New("KEY_F5").ToLocalChecked(),
                Nan::New(KEY_F5));
    target->Set(Nan::New("KEY_F6").ToLocalChecked(),
                Nan::New(KEY_F6));
    target->Set(Nan::New("KEY_F7").ToLocalChecked(),
                Nan::New(KEY_F7));
    target->Set(Nan::New("KEY_F8").ToLocalChecked(),
                Nan::New(KEY_F8));
    target->Set(Nan::New("KEY_F9").ToLocalChecked(),
                Nan::New(KEY_F9));
    target->Set(Nan::New("KEY_F10").ToLocalChecked(),
                Nan::New(KEY_F10));
    target->Set(Nan::New("KEY_NUMLOCK").ToLocalChecked(),
                Nan::New(KEY_NUMLOCK));
    target->Set(Nan::New("KEY_SCROLLLOCK").ToLocalChecked(),
                Nan::New(KEY_SCROLLLOCK));
    target->Set(Nan::New("KEY_KP7").ToLocalChecked(),
                Nan::New(KEY_KP7));
    target->Set(Nan::New("KEY_KP8").ToLocalChecked(),
                Nan::New(KEY_KP8));
    target->Set(Nan::New("KEY_KP9").ToLocalChecked(),
                Nan::New(KEY_KP9));
    target->Set(Nan::New("KEY_KPMINUS").ToLocalChecked(),
                Nan::New(KEY_KPMINUS));
    target->Set(Nan::New("KEY_KP4").ToLocalChecked(),
                Nan::New(KEY_KP4));
    target->Set(Nan::New("KEY_KP5").ToLocalChecked(),
                Nan::New(KEY_KP5));
    target->Set(Nan::New("KEY_KP6").ToLocalChecked(),
                Nan::New(KEY_KP6));
    target->Set(Nan::New("KEY_KPPLUS").ToLocalChecked(),
                Nan::New(KEY_KPPLUS));
    target->Set(Nan::New("KEY_KP1").ToLocalChecked(),
                Nan::New(KEY_KP1));
    target->Set(Nan::New("KEY_KP2").ToLocalChecked(),
                Nan::New(KEY_KP2));
    target->Set(Nan::New("KEY_KP3").ToLocalChecked(),
                Nan::New(KEY_KP3));
    target->Set(Nan::New("KEY_KP0").ToLocalChecked(),
                Nan::New(KEY_KP0));
    target->Set(Nan::New("KEY_KPDOT").ToLocalChecked(),
                Nan::New(KEY_KPDOT));
    target->Set(Nan::New("KEY_ZENKAKUHANKAKU").ToLocalChecked(),
                Nan::New(KEY_ZENKAKUHANKAKU));
    target->Set(Nan::New("KEY_102ND").ToLocalChecked(),
                Nan::New(KEY_102ND));
    target->Set(Nan::New("KEY_F11").ToLocalChecked(),
                Nan::New(KEY_F11));
    target->Set(Nan::New("KEY_F12").ToLocalChecked(),
                Nan::New(KEY_F12));
    target->Set(Nan::New("KEY_RO").ToLocalChecked(),
                Nan::New(KEY_RO));
    target->Set(Nan::New("KEY_KATAKANA").ToLocalChecked(),
                Nan::New(KEY_KATAKANA));
    target->Set(Nan::New("KEY_HIRAGANA").ToLocalChecked(),
                Nan::New(KEY_HIRAGANA));
    target->Set(Nan::New("KEY_HENKAN").ToLocalChecked(),
                Nan::New(KEY_HENKAN));
    target->Set(Nan::New("KEY_KATAKANAHIRAGANA").ToLocalChecked(),
                Nan::New(KEY_KATAKANAHIRAGANA));
    target->Set(Nan::New("KEY_MUHENKAN").ToLocalChecked(),
                Nan::New(KEY_MUHENKAN));
    target->Set(Nan::New("KEY_KPJPCOMMA").ToLocalChecked(),
                Nan::New(KEY_KPJPCOMMA));
    target->Set(Nan::New("KEY_KPENTER").ToLocalChecked(),
                Nan::New(KEY_KPENTER));
    target->Set(Nan::New("KEY_RIGHTCTRL").ToLocalChecked(),
                Nan::New(KEY_RIGHTCTRL));
    target->Set(Nan::New("KEY_KPSLASH").ToLocalChecked(),
                Nan::New(KEY_KPSLASH));
    target->Set(Nan::New("KEY_SYSRQ").ToLocalChecked(),
                Nan::New(KEY_SYSRQ));
    target->Set(Nan::New("KEY_RIGHTALT").ToLocalChecked(),
                Nan::New(KEY_RIGHTALT));
    target->Set(Nan::New("KEY_LINEFEED").ToLocalChecked(),
                Nan::New(KEY_LINEFEED));
    target->Set(Nan::New("KEY_HOME").ToLocalChecked(),
                Nan::New(KEY_HOME));
    target->Set(Nan::New("KEY_UP").ToLocalChecked(),
                Nan::New(KEY_UP));
    target->Set(Nan::New("KEY_PAGEUP").ToLocalChecked(),
                Nan::New(KEY_PAGEUP));
    target->Set(Nan::New("KEY_LEFT").ToLocalChecked(),
                Nan::New(KEY_LEFT));
    target->Set(Nan::New("KEY_RIGHT").ToLocalChecked(),
                Nan::New(KEY_RIGHT));
    target->Set(Nan::New("KEY_END").ToLocalChecked(),
                Nan::New(KEY_END));
    target->Set(Nan::New("KEY_DOWN").ToLocalChecked(),
                Nan::New(KEY_DOWN));
    target->Set(Nan::New("KEY_PAGEDOWN").ToLocalChecked(),
                Nan::New(KEY_PAGEDOWN));
    target->Set(Nan::New("KEY_INSERT").ToLocalChecked(),
                Nan::New(KEY_INSERT));
    target->Set(Nan::New("KEY_DELETE").ToLocalChecked(),
                Nan::New(KEY_DELETE));
    target->Set(Nan::New("KEY_MACRO").ToLocalChecked(),
                Nan::New(KEY_MACRO));
    target->Set(Nan::New("KEY_MUTE").ToLocalChecked(),
                Nan::New(KEY_MUTE));
    target->Set(Nan::New("KEY_VOLUMEDOWN").ToLocalChecked(),
                Nan::New(KEY_VOLUMEDOWN));
    target->Set(Nan::New("KEY_VOLUMEUP").ToLocalChecked(),
                Nan::New(KEY_VOLUMEUP));
    target->Set(Nan::New("KEY_POWER").ToLocalChecked(),
                Nan::New(KEY_POWER));
    target->Set(Nan::New("KEY_KPEQUAL").ToLocalChecked(),
                Nan::New(KEY_KPEQUAL));
    target->Set(Nan::New("KEY_KPPLUSMINUS").ToLocalChecked(),
                Nan::New(KEY_KPPLUSMINUS));
    target->Set(Nan::New("KEY_PAUSE").ToLocalChecked(),
                Nan::New(KEY_PAUSE));
    target->Set(Nan::New("KEY_SCALE").ToLocalChecked(),
                Nan::New(KEY_SCALE));
    target->Set(Nan::New("KEY_KPCOMMA").ToLocalChecked(),
                Nan::New(KEY_KPCOMMA));
    target->Set(Nan::New("KEY_HANGEUL").ToLocalChecked(),
                Nan::New(KEY_HANGEUL));
    target->Set(Nan::New("KEY_HANGUEL").ToLocalChecked(),
                Nan::New(KEY_HANGUEL));
    target->Set(Nan::New("KEY_HANJA").ToLocalChecked(),
                Nan::New(KEY_HANJA));
    target->Set(Nan::New("KEY_YEN").ToLocalChecked(),
                Nan::New(KEY_YEN));
    target->Set(Nan::New("KEY_LEFTMETA").ToLocalChecked(),
                Nan::New(KEY_LEFTMETA));
    target->Set(Nan::New("KEY_RIGHTMETA").ToLocalChecked(),
                Nan::New(KEY_RIGHTMETA));
    target->Set(Nan::New("KEY_COMPOSE").ToLocalChecked(),
                Nan::New(KEY_COMPOSE));
    target->Set(Nan::New("KEY_STOP").ToLocalChecked(),
                Nan::New(KEY_STOP));
    target->Set(Nan::New("KEY_AGAIN").ToLocalChecked(),
                Nan::New(KEY_AGAIN));
    target->Set(Nan::New("KEY_PROPS").ToLocalChecked(),
                Nan::New(KEY_PROPS));
    target->Set(Nan::New("KEY_UNDO").ToLocalChecked(),
                Nan::New(KEY_UNDO));
    target->Set(Nan::New("KEY_FRONT").ToLocalChecked(),
                Nan::New(KEY_FRONT));
    target->Set(Nan::New("KEY_COPY").ToLocalChecked(),
                Nan::New(KEY_COPY));
    target->Set(Nan::New("KEY_OPEN").ToLocalChecked(),
                Nan::New(KEY_OPEN));
    target->Set(Nan::New("KEY_PASTE").ToLocalChecked(),
                Nan::New(KEY_PASTE));
    target->Set(Nan::New("KEY_FIND").ToLocalChecked(),
                Nan::New(KEY_FIND));
    target->Set(Nan::New("KEY_CUT").ToLocalChecked(),
                Nan::New(KEY_CUT));
    target->Set(Nan::New("KEY_HELP").ToLocalChecked(),
                Nan::New(KEY_HELP));
    target->Set(Nan::New("KEY_MENU").ToLocalChecked(),
                Nan::New(KEY_MENU));
    target->Set(Nan::New("KEY_CALC").ToLocalChecked(),
                Nan::New(KEY_CALC));
    target->Set(Nan::New("KEY_SETUP").ToLocalChecked(),
                Nan::New(KEY_SETUP));
    target->Set(Nan::New("KEY_SLEEP").ToLocalChecked(),
                Nan::New(KEY_SLEEP));
    target->Set(Nan::New("KEY_WAKEUP").ToLocalChecked(),
                Nan::New(KEY_WAKEUP));
    target->Set(Nan::New("KEY_FILE").ToLocalChecked(),
                Nan::New(KEY_FILE));
    target->Set(Nan::New("KEY_SENDFILE").ToLocalChecked(),
                Nan::New(KEY_SENDFILE));
    target->Set(Nan::New("KEY_DELETEFILE").ToLocalChecked(),
                Nan::New(KEY_DELETEFILE));
    target->Set(Nan::New("KEY_XFER").ToLocalChecked(),
                Nan::New(KEY_XFER));
    target->Set(Nan::New("KEY_PROG1").ToLocalChecked(),
                Nan::New(KEY_PROG1));
    target->Set(Nan::New("KEY_PROG2").ToLocalChecked(),
                Nan::New(KEY_PROG2));
    target->Set(Nan::New("KEY_WWW").ToLocalChecked(),
                Nan::New(KEY_WWW));
    target->Set(Nan::New("KEY_MSDOS").ToLocalChecked(),
                Nan::New(KEY_MSDOS));
    target->Set(Nan::New("KEY_COFFEE").ToLocalChecked(),
                Nan::New(KEY_COFFEE));
    target->Set(Nan::New("KEY_SCREENLOCK").ToLocalChecked(),
                Nan::New(KEY_SCREENLOCK));
    target->Set(Nan::New("KEY_DIRECTION").ToLocalChecked(),
                Nan::New(KEY_DIRECTION));
    target->Set(Nan::New("KEY_CYCLEWINDOWS").ToLocalChecked(),
                Nan::New(KEY_CYCLEWINDOWS));
    target->Set(Nan::New("KEY_MAIL").ToLocalChecked(),
                Nan::New(KEY_MAIL));
    target->Set(Nan::New("KEY_BOOKMARKS").ToLocalChecked(),
                Nan::New(KEY_BOOKMARKS));
    target->Set(Nan::New("KEY_COMPUTER").ToLocalChecked(),
                Nan::New(KEY_COMPUTER));
    target->Set(Nan::New("KEY_BACK").ToLocalChecked(),
                Nan::New(KEY_BACK));
    target->Set(Nan::New("KEY_FORWARD").ToLocalChecked(),
                Nan::New(KEY_FORWARD));
    target->Set(Nan::New("KEY_CLOSECD").ToLocalChecked(),
                Nan::New(KEY_CLOSECD));
    target->Set(Nan::New("KEY_EJECTCD").ToLocalChecked(),
                Nan::New(KEY_EJECTCD));
    target->Set(Nan::New("KEY_EJECTCLOSECD").ToLocalChecked(),
                Nan::New(KEY_EJECTCLOSECD));
    target->Set(Nan::New("KEY_NEXTSONG").ToLocalChecked(),
                Nan::New(KEY_NEXTSONG));
    target->Set(Nan::New("KEY_PLAYPAUSE").ToLocalChecked(),
                Nan::New(KEY_PLAYPAUSE));
    target->Set(Nan::New("KEY_PREVIOUSSONG").ToLocalChecked(),
                Nan::New(KEY_PREVIOUSSONG));
    target->Set(Nan::New("KEY_STOPCD").ToLocalChecked(),
                Nan::New(KEY_STOPCD));
    target->Set(Nan::New("KEY_RECORD").ToLocalChecked(),
                Nan::New(KEY_RECORD));
    target->Set(Nan::New("KEY_REWIND").ToLocalChecked(),
                Nan::New(KEY_REWIND));
    target->Set(Nan::New("KEY_PHONE").ToLocalChecked(),
                Nan::New(KEY_PHONE));
    target->Set(Nan::New("KEY_ISO").ToLocalChecked(),
                Nan::New(KEY_ISO));
    target->Set(Nan::New("KEY_CONFIG").ToLocalChecked(),
                Nan::New(KEY_CONFIG));
    target->Set(Nan::New("KEY_HOMEPAGE").ToLocalChecked(),
                Nan::New(KEY_HOMEPAGE));
    target->Set(Nan::New("KEY_REFRESH").ToLocalChecked(),
                Nan::New(KEY_REFRESH));
    target->Set(Nan::New("KEY_EXIT").ToLocalChecked(),
                Nan::New(KEY_EXIT));
    target->Set(Nan::New("KEY_MOVE").ToLocalChecked(),
                Nan::New(KEY_MOVE));
    target->Set(Nan::New("KEY_EDIT").ToLocalChecked(),
                Nan::New(KEY_EDIT));
    target->Set(Nan::New("KEY_SCROLLUP").ToLocalChecked(),
                Nan::New(KEY_SCROLLUP));
    target->Set(Nan::New("KEY_SCROLLDOWN").ToLocalChecked(),
                Nan::New(KEY_SCROLLDOWN));
    target->Set(Nan::New("KEY_KPLEFTPAREN").ToLocalChecked(),
                Nan::New(KEY_KPLEFTPAREN));
    target->Set(Nan::New("KEY_KPRIGHTPAREN").ToLocalChecked(),
                Nan::New(KEY_KPRIGHTPAREN));
    target->Set(Nan::New("KEY_NEW").ToLocalChecked(),
                Nan::New(KEY_NEW));
    target->Set(Nan::New("KEY_REDO").ToLocalChecked(),
                Nan::New(KEY_REDO));
    target->Set(Nan::New("KEY_F13").ToLocalChecked(),
                Nan::New(KEY_F13));
    target->Set(Nan::New("KEY_F14").ToLocalChecked(),
                Nan::New(KEY_F14));
    target->Set(Nan::New("KEY_F15").ToLocalChecked(),
                Nan::New(KEY_F15));
    target->Set(Nan::New("KEY_F16").ToLocalChecked(),
                Nan::New(KEY_F16));
    target->Set(Nan::New("KEY_F17").ToLocalChecked(),
                Nan::New(KEY_F17));
    target->Set(Nan::New("KEY_F18").ToLocalChecked(),
                Nan::New(KEY_F18));
    target->Set(Nan::New("KEY_F19").ToLocalChecked(),
                Nan::New(KEY_F19));
    target->Set(Nan::New("KEY_F20").ToLocalChecked(),
                Nan::New(KEY_F20));
    target->Set(Nan::New("KEY_F21").ToLocalChecked(),
                Nan::New(KEY_F21));
    target->Set(Nan::New("KEY_F22").ToLocalChecked(),
                Nan::New(KEY_F22));
    target->Set(Nan::New("KEY_F23").ToLocalChecked(),
                Nan::New(KEY_F23));
    target->Set(Nan::New("KEY_F24").ToLocalChecked(),
                Nan::New(KEY_F24));
    target->Set(Nan::New("KEY_PLAYCD").ToLocalChecked(),
                Nan::New(KEY_PLAYCD));
    target->Set(Nan::New("KEY_PAUSECD").ToLocalChecked(),
                Nan::New(KEY_PAUSECD));
    target->Set(Nan::New("KEY_PROG3").ToLocalChecked(),
                Nan::New(KEY_PROG3));
    target->Set(Nan::New("KEY_PROG4").ToLocalChecked(),
                Nan::New(KEY_PROG4));
    target->Set(Nan::New("KEY_DASHBOARD").ToLocalChecked(),
                Nan::New(KEY_DASHBOARD));
    target->Set(Nan::New("KEY_SUSPEND").ToLocalChecked(),
                Nan::New(KEY_SUSPEND));
    target->Set(Nan::New("KEY_CLOSE").ToLocalChecked(),
                Nan::New(KEY_CLOSE));
    target->Set(Nan::New("KEY_PLAY").ToLocalChecked(),
                Nan::New(KEY_PLAY));
    target->Set(Nan::New("KEY_FASTFORWARD").ToLocalChecked(),
                Nan::New(KEY_FASTFORWARD));
    target->Set(Nan::New("KEY_BASSBOOST").ToLocalChecked(),
                Nan::New(KEY_BASSBOOST));
    target->Set(Nan::New("KEY_PRINT").ToLocalChecked(),
                Nan::New(KEY_PRINT));
    target->Set(Nan::New("KEY_HP").ToLocalChecked(),
                Nan::New(KEY_HP));
    target->Set(Nan::New("KEY_CAMERA").ToLocalChecked(),
                Nan::New(KEY_CAMERA));
    target->Set(Nan::New("KEY_SOUND").ToLocalChecked(),
                Nan::New(KEY_SOUND));
    target->Set(Nan::New("KEY_QUESTION").ToLocalChecked(),
                Nan::New(KEY_QUESTION));
    target->Set(Nan::New("KEY_EMAIL").ToLocalChecked(),
                Nan::New(KEY_EMAIL));
    target->Set(Nan::New("KEY_CHAT").ToLocalChecked(),
                Nan::New(KEY_CHAT));
    target->Set(Nan::New("KEY_SEARCH").ToLocalChecked(),
                Nan::New(KEY_SEARCH));
    target->Set(Nan::New("KEY_CONNECT").ToLocalChecked(),
                Nan::New(KEY_CONNECT));
    target->Set(Nan::New("KEY_FINANCE").ToLocalChecked(),
                Nan::New(KEY_FINANCE));
    target->Set(Nan::New("KEY_SPORT").ToLocalChecked(),
                Nan::New(KEY_SPORT));
    target->Set(Nan::New("KEY_SHOP").ToLocalChecked(),
                Nan::New(KEY_SHOP));
    target->Set(Nan::New("KEY_ALTERASE").ToLocalChecked(),
                Nan::New(KEY_ALTERASE));
    target->Set(Nan::New("KEY_CANCEL").ToLocalChecked(),
                Nan::New(KEY_CANCEL));
    target->Set(Nan::New("KEY_BRIGHTNESSDOWN").ToLocalChecked(),
                Nan::New(KEY_BRIGHTNESSDOWN));
    target->Set(Nan::New("KEY_BRIGHTNESSUP").ToLocalChecked(),
                Nan::New(KEY_BRIGHTNESSUP));
    target->Set(Nan::New("KEY_MEDIA").ToLocalChecked(),
                Nan::New(KEY_MEDIA));
    target->Set(Nan::New("KEY_SWITCHVIDEOMODE").ToLocalChecked(),
                Nan::New(KEY_SWITCHVIDEOMODE));
    target->Set(Nan::New("KEY_KBDILLUMTOGGLE").ToLocalChecked(),
                Nan::New(KEY_KBDILLUMTOGGLE));
    target->Set(Nan::New("KEY_KBDILLUMDOWN").ToLocalChecked(),
                Nan::New(KEY_KBDILLUMDOWN));
    target->Set(Nan::New("KEY_KBDILLUMUP").ToLocalChecked(),
                Nan::New(KEY_KBDILLUMUP));
    target->Set(Nan::New("KEY_SEND").ToLocalChecked(),
                Nan::New(KEY_SEND));
    target->Set(Nan::New("KEY_REPLY").ToLocalChecked(),
                Nan::New(KEY_REPLY));
    target->Set(Nan::New("KEY_FORWARDMAIL").ToLocalChecked(),
                Nan::New(KEY_FORWARDMAIL));
    target->Set(Nan::New("KEY_SAVE").ToLocalChecked(),
                Nan::New(KEY_SAVE));
    target->Set(Nan::New("KEY_DOCUMENTS").ToLocalChecked(),
                Nan::New(KEY_DOCUMENTS));
    target->Set(Nan::New("KEY_BATTERY").ToLocalChecked(),
                Nan::New(KEY_BATTERY));
    target->Set(Nan::New("KEY_BLUETOOTH").ToLocalChecked(),
                Nan::New(KEY_BLUETOOTH));
    target->Set(Nan::New("KEY_WLAN").ToLocalChecked(),
                Nan::New(KEY_WLAN));
    target->Set(Nan::New("KEY_UWB").ToLocalChecked(),
                Nan::New(KEY_UWB));
    target->Set(Nan::New("KEY_UNKNOWN").ToLocalChecked(),
                Nan::New(KEY_UNKNOWN));
    target->Set(Nan::New("KEY_VIDEO_NEXT").ToLocalChecked(),
                Nan::New(KEY_VIDEO_NEXT));
    target->Set(Nan::New("KEY_VIDEO_PREV").ToLocalChecked(),
                Nan::New(KEY_VIDEO_PREV));
    target->Set(Nan::New("KEY_BRIGHTNESS_CYCLE").ToLocalChecked(),
                Nan::New(KEY_BRIGHTNESS_CYCLE));
    target->Set(Nan::New("KEY_BRIGHTNESS_ZERO").ToLocalChecked(),
                Nan::New(KEY_BRIGHTNESS_ZERO));
    target->Set(Nan::New("KEY_DISPLAY_OFF").ToLocalChecked(),
                Nan::New(KEY_DISPLAY_OFF));
    target->Set(Nan::New("KEY_WIMAX").ToLocalChecked(),
                Nan::New(KEY_WIMAX));
    target->Set(Nan::New("KEY_RFKILL").ToLocalChecked(),
                Nan::New(KEY_RFKILL));
    target->Set(Nan::New("KEY_MICMUTE").ToLocalChecked(),
                Nan::New(KEY_MICMUTE));
    target->Set(Nan::New("BTN_MISC").ToLocalChecked(),
                Nan::New(BTN_MISC));
    target->Set(Nan::New("BTN_0").ToLocalChecked(),
                Nan::New(BTN_0));
    target->Set(Nan::New("BTN_1").ToLocalChecked(),
                Nan::New(BTN_1));
    target->Set(Nan::New("BTN_2").ToLocalChecked(),
                Nan::New(BTN_2));
    target->Set(Nan::New("BTN_3").ToLocalChecked(),
                Nan::New(BTN_3));
    target->Set(Nan::New("BTN_4").ToLocalChecked(),
                Nan::New(BTN_4));
    target->Set(Nan::New("BTN_5").ToLocalChecked(),
                Nan::New(BTN_5));
    target->Set(Nan::New("BTN_6").ToLocalChecked(),
                Nan::New(BTN_6));
    target->Set(Nan::New("BTN_7").ToLocalChecked(),
                Nan::New(BTN_7));
    target->Set(Nan::New("BTN_8").ToLocalChecked(),
                Nan::New(BTN_8));
    target->Set(Nan::New("BTN_9").ToLocalChecked(),
                Nan::New(BTN_9));
    target->Set(Nan::New("BTN_MOUSE").ToLocalChecked(),
                Nan::New(BTN_MOUSE));
    target->Set(Nan::New("BTN_LEFT").ToLocalChecked(),
                Nan::New(BTN_LEFT));
    target->Set(Nan::New("BTN_RIGHT").ToLocalChecked(),
                Nan::New(BTN_RIGHT));
    target->Set(Nan::New("BTN_MIDDLE").ToLocalChecked(),
                Nan::New(BTN_MIDDLE));
    target->Set(Nan::New("BTN_SIDE").ToLocalChecked(),
                Nan::New(BTN_SIDE));
    target->Set(Nan::New("BTN_EXTRA").ToLocalChecked(),
                Nan::New(BTN_EXTRA));
    target->Set(Nan::New("BTN_FORWARD").ToLocalChecked(),
                Nan::New(BTN_FORWARD));
    target->Set(Nan::New("BTN_BACK").ToLocalChecked(),
                Nan::New(BTN_BACK));
    target->Set(Nan::New("BTN_TASK").ToLocalChecked(),
                Nan::New(BTN_TASK));
    target->Set(Nan::New("BTN_JOYSTICK").ToLocalChecked(),
                Nan::New(BTN_JOYSTICK));
    target->Set(Nan::New("BTN_TRIGGER").ToLocalChecked(),
                Nan::New(BTN_TRIGGER));
    target->Set(Nan::New("BTN_THUMB").ToLocalChecked(),
                Nan::New(BTN_THUMB));
    target->Set(Nan::New("BTN_THUMB2").ToLocalChecked(),
                Nan::New(BTN_THUMB2));
    target->Set(Nan::New("BTN_TOP").ToLocalChecked(),
                Nan::New(BTN_TOP));
    target->Set(Nan::New("BTN_TOP2").ToLocalChecked(),
                Nan::New(BTN_TOP2));
    target->Set(Nan::New("BTN_PINKIE").ToLocalChecked(),
                Nan::New(BTN_PINKIE));
    target->Set(Nan::New("BTN_BASE").ToLocalChecked(),
                Nan::New(BTN_BASE));
    target->Set(Nan::New("BTN_BASE2").ToLocalChecked(),
                Nan::New(BTN_BASE2));
    target->Set(Nan::New("BTN_BASE3").ToLocalChecked(),
                Nan::New(BTN_BASE3));
    target->Set(Nan::New("BTN_BASE4").ToLocalChecked(),
                Nan::New(BTN_BASE4));
    target->Set(Nan::New("BTN_BASE5").ToLocalChecked(),
                Nan::New(BTN_BASE5));
    target->Set(Nan::New("BTN_BASE6").ToLocalChecked(),
                Nan::New(BTN_BASE6));
    target->Set(Nan::New("BTN_DEAD").ToLocalChecked(),
                Nan::New(BTN_DEAD));
    target->Set(Nan::New("BTN_GAMEPAD").ToLocalChecked(),
                Nan::New(BTN_GAMEPAD));
    target->Set(Nan::New("BTN_A").ToLocalChecked(),
                Nan::New(BTN_A));
    target->Set(Nan::New("BTN_B").ToLocalChecked(),
                Nan::New(BTN_B));
    target->Set(Nan::New("BTN_C").ToLocalChecked(),
                Nan::New(BTN_C));
    target->Set(Nan::New("BTN_X").ToLocalChecked(),
                Nan::New(BTN_X));
    target->Set(Nan::New("BTN_Y").ToLocalChecked(),
                Nan::New(BTN_Y));
    target->Set(Nan::New("BTN_Z").ToLocalChecked(),
                Nan::New(BTN_Z));
    target->Set(Nan::New("BTN_TL").ToLocalChecked(),
                Nan::New(BTN_TL));
    target->Set(Nan::New("BTN_TR").ToLocalChecked(),
                Nan::New(BTN_TR));
    target->Set(Nan::New("BTN_TL2").ToLocalChecked(),
                Nan::New(BTN_TL2));
    target->Set(Nan::New("BTN_TR2").ToLocalChecked(),
                Nan::New(BTN_TR2));
    target->Set(Nan::New("BTN_SELECT").ToLocalChecked(),
                Nan::New(BTN_SELECT));
    target->Set(Nan::New("BTN_START").ToLocalChecked(),
                Nan::New(BTN_START));
    target->Set(Nan::New("BTN_MODE").ToLocalChecked(),
                Nan::New(BTN_MODE));
    target->Set(Nan::New("BTN_THUMBL").ToLocalChecked(),
                Nan::New(BTN_THUMBL));
    target->Set(Nan::New("BTN_THUMBR").ToLocalChecked(),
                Nan::New(BTN_THUMBR));
    target->Set(Nan::New("BTN_DIGI").ToLocalChecked(),
                Nan::New(BTN_DIGI));
    target->Set(Nan::New("BTN_TOOL_PEN").ToLocalChecked(),
                Nan::New(BTN_TOOL_PEN));
    target->Set(Nan::New("BTN_TOOL_RUBBER").ToLocalChecked(),
                Nan::New(BTN_TOOL_RUBBER));
    target->Set(Nan::New("BTN_TOOL_BRUSH").ToLocalChecked(),
                Nan::New(BTN_TOOL_BRUSH));
    target->Set(Nan::New("BTN_TOOL_PENCIL").ToLocalChecked(),
                Nan::New(BTN_TOOL_PENCIL));
    target->Set(Nan::New("BTN_TOOL_AIRBRUSH").ToLocalChecked(),
                Nan::New(BTN_TOOL_AIRBRUSH));
    target->Set(Nan::New("BTN_TOOL_FINGER").ToLocalChecked(),
                Nan::New(BTN_TOOL_FINGER));
    target->Set(Nan::New("BTN_TOOL_MOUSE").ToLocalChecked(),
                Nan::New(BTN_TOOL_MOUSE));
    target->Set(Nan::New("BTN_TOOL_LENS").ToLocalChecked(),
                Nan::New(BTN_TOOL_LENS));
    target->Set(Nan::New("BTN_TOOL_QUINTTAP").ToLocalChecked(),
                Nan::New(BTN_TOOL_QUINTTAP));
    target->Set(Nan::New("BTN_TOUCH").ToLocalChecked(),
                Nan::New(BTN_TOUCH));
    target->Set(Nan::New("BTN_STYLUS").ToLocalChecked(),
                Nan::New(BTN_STYLUS));
    target->Set(Nan::New("BTN_STYLUS2").ToLocalChecked(),
                Nan::New(BTN_STYLUS2));
    target->Set(Nan::New("BTN_TOOL_DOUBLETAP").ToLocalChecked(),
                Nan::New(BTN_TOOL_DOUBLETAP));
    target->Set(Nan::New("BTN_TOOL_TRIPLETAP").ToLocalChecked(),
                Nan::New(BTN_TOOL_TRIPLETAP));
    target->Set(Nan::New("BTN_TOOL_QUADTAP").ToLocalChecked(),
                Nan::New(BTN_TOOL_QUADTAP));
    target->Set(Nan::New("BTN_WHEEL").ToLocalChecked(),
                Nan::New(BTN_WHEEL));
    target->Set(Nan::New("BTN_GEAR_DOWN").ToLocalChecked(),
                Nan::New(BTN_GEAR_DOWN));
    target->Set(Nan::New("BTN_GEAR_UP").ToLocalChecked(),
                Nan::New(BTN_GEAR_UP));
    target->Set(Nan::New("KEY_OK").ToLocalChecked(),
                Nan::New(KEY_OK));
    target->Set(Nan::New("KEY_SELECT").ToLocalChecked(),
                Nan::New(KEY_SELECT));
    target->Set(Nan::New("KEY_GOTO").ToLocalChecked(),
                Nan::New(KEY_GOTO));
    target->Set(Nan::New("KEY_CLEAR").ToLocalChecked(),
                Nan::New(KEY_CLEAR));
    target->Set(Nan::New("KEY_POWER2").ToLocalChecked(),
                Nan::New(KEY_POWER2));
    target->Set(Nan::New("KEY_OPTION").ToLocalChecked(),
                Nan::New(KEY_OPTION));
    target->Set(Nan::New("KEY_INFO").ToLocalChecked(),
                Nan::New(KEY_INFO));
    target->Set(Nan::New("KEY_TIME").ToLocalChecked(),
                Nan::New(KEY_TIME));
    target->Set(Nan::New("KEY_VENDOR").ToLocalChecked(),
                Nan::New(KEY_VENDOR));
    target->Set(Nan::New("KEY_ARCHIVE").ToLocalChecked(),
                Nan::New(KEY_ARCHIVE));
    target->Set(Nan::New("KEY_PROGRAM").ToLocalChecked(),
                Nan::New(KEY_PROGRAM));
    target->Set(Nan::New("KEY_CHANNEL").ToLocalChecked(),
                Nan::New(KEY_CHANNEL));
    target->Set(Nan::New("KEY_FAVORITES").ToLocalChecked(),
                Nan::New(KEY_FAVORITES));
    target->Set(Nan::New("KEY_EPG").ToLocalChecked(),
                Nan::New(KEY_EPG));
    target->Set(Nan::New("KEY_PVR").ToLocalChecked(),
                Nan::New(KEY_PVR));
    target->Set(Nan::New("KEY_MHP").ToLocalChecked(),
                Nan::New(KEY_MHP));
    target->Set(Nan::New("KEY_LANGUAGE").ToLocalChecked(),
                Nan::New(KEY_LANGUAGE));
    target->Set(Nan::New("KEY_TITLE").ToLocalChecked(),
                Nan::New(KEY_TITLE));
    target->Set(Nan::New("KEY_SUBTITLE").ToLocalChecked(),
                Nan::New(KEY_SUBTITLE));
    target->Set(Nan::New("KEY_ANGLE").ToLocalChecked(),
                Nan::New(KEY_ANGLE));
    target->Set(Nan::New("KEY_ZOOM").ToLocalChecked(),
                Nan::New(KEY_ZOOM));
    target->Set(Nan::New("KEY_MODE").ToLocalChecked(),
                Nan::New(KEY_MODE));
    target->Set(Nan::New("KEY_KEYBOARD").ToLocalChecked(),
                Nan::New(KEY_KEYBOARD));
    target->Set(Nan::New("KEY_SCREEN").ToLocalChecked(),
                Nan::New(KEY_SCREEN));
    target->Set(Nan::New("KEY_PC").ToLocalChecked(),
                Nan::New(KEY_PC));
    target->Set(Nan::New("KEY_TV").ToLocalChecked(),
                Nan::New(KEY_TV));
    target->Set(Nan::New("KEY_TV2").ToLocalChecked(),
                Nan::New(KEY_TV2));
    target->Set(Nan::New("KEY_VCR").ToLocalChecked(),
                Nan::New(KEY_VCR));
    target->Set(Nan::New("KEY_VCR2").ToLocalChecked(),
                Nan::New(KEY_VCR2));
    target->Set(Nan::New("KEY_SAT").ToLocalChecked(),
                Nan::New(KEY_SAT));
    target->Set(Nan::New("KEY_SAT2").ToLocalChecked(),
                Nan::New(KEY_SAT2));
    target->Set(Nan::New("KEY_CD").ToLocalChecked(),
                Nan::New(KEY_CD));
    target->Set(Nan::New("KEY_TAPE").ToLocalChecked(),
                Nan::New(KEY_TAPE));
    target->Set(Nan::New("KEY_RADIO").ToLocalChecked(),
                Nan::New(KEY_RADIO));
    target->Set(Nan::New("KEY_TUNER").ToLocalChecked(),
                Nan::New(KEY_TUNER));
    target->Set(Nan::New("KEY_PLAYER").ToLocalChecked(),
                Nan::New(KEY_PLAYER));
    target->Set(Nan::New("KEY_TEXT").ToLocalChecked(),
                Nan::New(KEY_TEXT));
    target->Set(Nan::New("KEY_DVD").ToLocalChecked(),
                Nan::New(KEY_DVD));
    target->Set(Nan::New("KEY_AUX").ToLocalChecked(),
                Nan::New(KEY_AUX));
    target->Set(Nan::New("KEY_MP3").ToLocalChecked(),
                Nan::New(KEY_MP3));
    target->Set(Nan::New("KEY_AUDIO").ToLocalChecked(),
                Nan::New(KEY_AUDIO));
    target->Set(Nan::New("KEY_VIDEO").ToLocalChecked(),
                Nan::New(KEY_VIDEO));
    target->Set(Nan::New("KEY_DIRECTORY").ToLocalChecked(),
                Nan::New(KEY_DIRECTORY));
    target->Set(Nan::New("KEY_LIST").ToLocalChecked(),
                Nan::New(KEY_LIST));
    target->Set(Nan::New("KEY_MEMO").ToLocalChecked(),
                Nan::New(KEY_MEMO));
    target->Set(Nan::New("KEY_CALENDAR").ToLocalChecked(),
                Nan::New(KEY_CALENDAR));
    target->Set(Nan::New("KEY_RED").ToLocalChecked(),
                Nan::New(KEY_RED));
    target->Set(Nan::New("KEY_GREEN").ToLocalChecked(),
                Nan::New(KEY_GREEN));
    target->Set(Nan::New("KEY_YELLOW").ToLocalChecked(),
                Nan::New(KEY_YELLOW));
    target->Set(Nan::New("KEY_BLUE").ToLocalChecked(),
                Nan::New(KEY_BLUE));
    target->Set(Nan::New("KEY_CHANNELUP").ToLocalChecked(),
                Nan::New(KEY_CHANNELUP));
    target->Set(Nan::New("KEY_CHANNELDOWN").ToLocalChecked(),
                Nan::New(KEY_CHANNELDOWN));
    target->Set(Nan::New("KEY_FIRST").ToLocalChecked(),
                Nan::New(KEY_FIRST));
    target->Set(Nan::New("KEY_LAST").ToLocalChecked(),
                Nan::New(KEY_LAST));
    target->Set(Nan::New("KEY_AB").ToLocalChecked(),
                Nan::New(KEY_AB));
    target->Set(Nan::New("KEY_NEXT").ToLocalChecked(),
                Nan::New(KEY_NEXT));
    target->Set(Nan::New("KEY_RESTART").ToLocalChecked(),
                Nan::New(KEY_RESTART));
    target->Set(Nan::New("KEY_SLOW").ToLocalChecked(),
                Nan::New(KEY_SLOW));
    target->Set(Nan::New("KEY_SHUFFLE").ToLocalChecked(),
                Nan::New(KEY_SHUFFLE));
    target->Set(Nan::New("KEY_BREAK").ToLocalChecked(),
                Nan::New(KEY_BREAK));
    target->Set(Nan::New("KEY_PREVIOUS").ToLocalChecked(),
                Nan::New(KEY_PREVIOUS));
    target->Set(Nan::New("KEY_DIGITS").ToLocalChecked(),
                Nan::New(KEY_DIGITS));
    target->Set(Nan::New("KEY_TEEN").ToLocalChecked(),
                Nan::New(KEY_TEEN));
    target->Set(Nan::New("KEY_TWEN").ToLocalChecked(),
                Nan::New(KEY_TWEN));
    target->Set(Nan::New("KEY_VIDEOPHONE").ToLocalChecked(),
                Nan::New(KEY_VIDEOPHONE));
    target->Set(Nan::New("KEY_GAMES").ToLocalChecked(),
                Nan::New(KEY_GAMES));
    target->Set(Nan::New("KEY_ZOOMIN").ToLocalChecked(),
                Nan::New(KEY_ZOOMIN));
    target->Set(Nan::New("KEY_ZOOMOUT").ToLocalChecked(),
                Nan::New(KEY_ZOOMOUT));
    target->Set(Nan::New("KEY_ZOOMRESET").ToLocalChecked(),
                Nan::New(KEY_ZOOMRESET));
    target->Set(Nan::New("KEY_WORDPROCESSOR").ToLocalChecked(),
                Nan::New(KEY_WORDPROCESSOR));
    target->Set(Nan::New("KEY_EDITOR").ToLocalChecked(),
                Nan::New(KEY_EDITOR));
    target->Set(Nan::New("KEY_SPREADSHEET").ToLocalChecked(),
                Nan::New(KEY_SPREADSHEET));
    target->Set(Nan::New("KEY_GRAPHICSEDITOR").ToLocalChecked(),
                Nan::New(KEY_GRAPHICSEDITOR));
    target->Set(Nan::New("KEY_PRESENTATION").ToLocalChecked(),
                Nan::New(KEY_PRESENTATION));
    target->Set(Nan::New("KEY_DATABASE").ToLocalChecked(),
                Nan::New(KEY_DATABASE));
    target->Set(Nan::New("KEY_NEWS").ToLocalChecked(),
                Nan::New(KEY_NEWS));
    target->Set(Nan::New("KEY_VOICEMAIL").ToLocalChecked(),
                Nan::New(KEY_VOICEMAIL));
    target->Set(Nan::New("KEY_ADDRESSBOOK").ToLocalChecked(),
                Nan::New(KEY_ADDRESSBOOK));
    target->Set(Nan::New("KEY_MESSENGER").ToLocalChecked(),
                Nan::New(KEY_MESSENGER));
    target->Set(Nan::New("KEY_DISPLAYTOGGLE").ToLocalChecked(),
                Nan::New(KEY_DISPLAYTOGGLE));
    target->Set(Nan::New("KEY_SPELLCHECK").ToLocalChecked(),
                Nan::New(KEY_SPELLCHECK));
    target->Set(Nan::New("KEY_LOGOFF").ToLocalChecked(),
                Nan::New(KEY_LOGOFF));
    target->Set(Nan::New("KEY_DOLLAR").ToLocalChecked(),
                Nan::New(KEY_DOLLAR));
    target->Set(Nan::New("KEY_EURO").ToLocalChecked(),
                Nan::New(KEY_EURO));
    target->Set(Nan::New("KEY_FRAMEBACK").ToLocalChecked(),
                Nan::New(KEY_FRAMEBACK));
    target->Set(Nan::New("KEY_FRAMEFORWARD").ToLocalChecked(),
                Nan::New(KEY_FRAMEFORWARD));
    target->Set(Nan::New("KEY_CONTEXT_MENU").ToLocalChecked(),
                Nan::New(KEY_CONTEXT_MENU));
    target->Set(Nan::New("KEY_MEDIA_REPEAT").ToLocalChecked(),
                Nan::New(KEY_MEDIA_REPEAT));
    target->Set(Nan::New("KEY_10CHANNELSUP").ToLocalChecked(),
                Nan::New(KEY_10CHANNELSUP));
    target->Set(Nan::New("KEY_10CHANNELSDOWN").ToLocalChecked(),
                Nan::New(KEY_10CHANNELSDOWN));
    target->Set(Nan::New("KEY_IMAGES").ToLocalChecked(),
                Nan::New(KEY_IMAGES));
    target->Set(Nan::New("KEY_DEL_EOL").ToLocalChecked(),
                Nan::New(KEY_DEL_EOL));
    target->Set(Nan::New("KEY_DEL_EOS").ToLocalChecked(),
                Nan::New(KEY_DEL_EOS));
    target->Set(Nan::New("KEY_INS_LINE").ToLocalChecked(),
                Nan::New(KEY_INS_LINE));
    target->Set(Nan::New("KEY_DEL_LINE").ToLocalChecked(),
                Nan::New(KEY_DEL_LINE));
    target->Set(Nan::New("KEY_FN").ToLocalChecked(),
                Nan::New(KEY_FN));
    target->Set(Nan::New("KEY_FN_ESC").ToLocalChecked(),
                Nan::New(KEY_FN_ESC));
    target->Set(Nan::New("KEY_FN_F1").ToLocalChecked(),
                Nan::New(KEY_FN_F1));
    target->Set(Nan::New("KEY_FN_F2").ToLocalChecked(),
                Nan::New(KEY_FN_F2));
    target->Set(Nan::New("KEY_FN_F3").ToLocalChecked(),
                Nan::New(KEY_FN_F3));
    target->Set(Nan::New("KEY_FN_F4").ToLocalChecked(),
                Nan::New(KEY_FN_F4));
    target->Set(Nan::New("KEY_FN_F5").ToLocalChecked(),
                Nan::New(KEY_FN_F5));
    target->Set(Nan::New("KEY_FN_F6").ToLocalChecked(),
                Nan::New(KEY_FN_F6));
    target->Set(Nan::New("KEY_FN_F7").ToLocalChecked(),
                Nan::New(KEY_FN_F7));
    target->Set(Nan::New("KEY_FN_F8").ToLocalChecked(),
                Nan::New(KEY_FN_F8));
    target->Set(Nan::New("KEY_FN_F9").ToLocalChecked(),
                Nan::New(KEY_FN_F9));
    target->Set(Nan::New("KEY_FN_F10").ToLocalChecked(),
                Nan::New(KEY_FN_F10));
    target->Set(Nan::New("KEY_FN_F11").ToLocalChecked(),
                Nan::New(KEY_FN_F11));
    target->Set(Nan::New("KEY_FN_F12").ToLocalChecked(),
                Nan::New(KEY_FN_F12));
    target->Set(Nan::New("KEY_FN_1").ToLocalChecked(),
                Nan::New(KEY_FN_1));
    target->Set(Nan::New("KEY_FN_2").ToLocalChecked(),
                Nan::New(KEY_FN_2));
    target->Set(Nan::New("KEY_FN_D").ToLocalChecked(),
                Nan::New(KEY_FN_D));
    target->Set(Nan::New("KEY_FN_E").ToLocalChecked(),
                Nan::New(KEY_FN_E));
    target->Set(Nan::New("KEY_FN_F").ToLocalChecked(),
                Nan::New(KEY_FN_F));
    target->Set(Nan::New("KEY_FN_S").ToLocalChecked(),
                Nan::New(KEY_FN_S));
    target->Set(Nan::New("KEY_FN_B").ToLocalChecked(),
                Nan::New(KEY_FN_B));
    target->Set(Nan::New("KEY_BRL_DOT1").ToLocalChecked(),
                Nan::New(KEY_BRL_DOT1));
    target->Set(Nan::New("KEY_BRL_DOT2").ToLocalChecked(),
                Nan::New(KEY_BRL_DOT2));
    target->Set(Nan::New("KEY_BRL_DOT3").ToLocalChecked(),
                Nan::New(KEY_BRL_DOT3));
    target->Set(Nan::New("KEY_BRL_DOT4").ToLocalChecked(),
                Nan::New(KEY_BRL_DOT4));
    target->Set(Nan::New("KEY_BRL_DOT5").ToLocalChecked(),
                Nan::New(KEY_BRL_DOT5));
    target->Set(Nan::New("KEY_BRL_DOT6").ToLocalChecked(),
                Nan::New(KEY_BRL_DOT6));
    target->Set(Nan::New("KEY_BRL_DOT7").ToLocalChecked(),
                Nan::New(KEY_BRL_DOT7));
    target->Set(Nan::New("KEY_BRL_DOT8").ToLocalChecked(),
                Nan::New(KEY_BRL_DOT8));
    target->Set(Nan::New("KEY_BRL_DOT9").ToLocalChecked(),
                Nan::New(KEY_BRL_DOT9));
    target->Set(Nan::New("KEY_BRL_DOT10").ToLocalChecked(),
                Nan::New(KEY_BRL_DOT10));
    target->Set(Nan::New("KEY_NUMERIC_0").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_0));
    target->Set(Nan::New("KEY_NUMERIC_1").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_1));
    target->Set(Nan::New("KEY_NUMERIC_2").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_2));
    target->Set(Nan::New("KEY_NUMERIC_3").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_3));
    target->Set(Nan::New("KEY_NUMERIC_4").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_4));
    target->Set(Nan::New("KEY_NUMERIC_5").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_5));
    target->Set(Nan::New("KEY_NUMERIC_6").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_6));
    target->Set(Nan::New("KEY_NUMERIC_7").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_7));
    target->Set(Nan::New("KEY_NUMERIC_8").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_8));
    target->Set(Nan::New("KEY_NUMERIC_9").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_9));
    target->Set(Nan::New("KEY_NUMERIC_STAR").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_STAR));
    target->Set(Nan::New("KEY_NUMERIC_POUND").ToLocalChecked(),
                Nan::New(KEY_NUMERIC_POUND));
    target->Set(Nan::New("KEY_CAMERA_FOCUS").ToLocalChecked(),
                Nan::New(KEY_CAMERA_FOCUS));
    target->Set(Nan::New("KEY_WPS_BUTTON").ToLocalChecked(),
                Nan::New(KEY_WPS_BUTTON));
    target->Set(Nan::New("KEY_TOUCHPAD_TOGGLE").ToLocalChecked(),
                Nan::New(KEY_TOUCHPAD_TOGGLE));
    target->Set(Nan::New("KEY_TOUCHPAD_ON").ToLocalChecked(),
                Nan::New(KEY_TOUCHPAD_ON));
    target->Set(Nan::New("KEY_TOUCHPAD_OFF").ToLocalChecked(),
                Nan::New(KEY_TOUCHPAD_OFF));
    target->Set(Nan::New("KEY_CAMERA_ZOOMIN").ToLocalChecked(),
                Nan::New(KEY_CAMERA_ZOOMIN));
    target->Set(Nan::New("KEY_CAMERA_ZOOMOUT").ToLocalChecked(),
                Nan::New(KEY_CAMERA_ZOOMOUT));
    target->Set(Nan::New("KEY_CAMERA_UP").ToLocalChecked(),
                Nan::New(KEY_CAMERA_UP));
    target->Set(Nan::New("KEY_CAMERA_DOWN").ToLocalChecked(),
                Nan::New(KEY_CAMERA_DOWN));
    target->Set(Nan::New("KEY_CAMERA_LEFT").ToLocalChecked(),
                Nan::New(KEY_CAMERA_LEFT));
    target->Set(Nan::New("KEY_CAMERA_RIGHT").ToLocalChecked(),
                Nan::New(KEY_CAMERA_RIGHT));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY1").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY1));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY2").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY2));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY3").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY3));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY4").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY4));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY5").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY5));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY6").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY6));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY7").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY7));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY8").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY8));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY9").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY9));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY10").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY10));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY11").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY11));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY12").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY12));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY13").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY13));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY14").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY14));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY15").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY15));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY16").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY16));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY17").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY17));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY18").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY18));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY19").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY19));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY20").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY20));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY21").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY21));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY22").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY22));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY23").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY23));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY24").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY24));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY25").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY25));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY26").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY26));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY27").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY27));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY28").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY28));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY29").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY29));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY30").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY30));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY31").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY31));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY32").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY32));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY33").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY33));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY34").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY34));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY35").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY35));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY36").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY36));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY37").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY37));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY38").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY38));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY39").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY39));
    target->Set(Nan::New("BTN_TRIGGER_HAPPY40").ToLocalChecked(),
                Nan::New(BTN_TRIGGER_HAPPY40));
    target->Set(Nan::New("KEY_MIN_INTERESTING").ToLocalChecked(),
                Nan::New(KEY_MIN_INTERESTING));
    target->Set(Nan::New("KEY_MAX").ToLocalChecked(),
                Nan::New(KEY_MAX));
    target->Set(Nan::New("KEY_CNT").ToLocalChecked(),
                Nan::New(KEY_CNT));
    target->Set(Nan::New("REL_X").ToLocalChecked(),
                Nan::New(REL_X));
    target->Set(Nan::New("REL_Y").ToLocalChecked(),
                Nan::New(REL_Y));
    target->Set(Nan::New("REL_Z").ToLocalChecked(),
                Nan::New(REL_Z));
    target->Set(Nan::New("REL_RX").ToLocalChecked(),
                Nan::New(REL_RX));
    target->Set(Nan::New("REL_RY").ToLocalChecked(),
                Nan::New(REL_RY));
    target->Set(Nan::New("REL_RZ").ToLocalChecked(),
                Nan::New(REL_RZ));
    target->Set(Nan::New("REL_HWHEEL").ToLocalChecked(),
                Nan::New(REL_HWHEEL));
    target->Set(Nan::New("REL_DIAL").ToLocalChecked(),
                Nan::New(REL_DIAL));
    target->Set(Nan::New("REL_WHEEL").ToLocalChecked(),
                Nan::New(REL_WHEEL));
    target->Set(Nan::New("REL_MISC").ToLocalChecked(),
                Nan::New(REL_MISC));
    target->Set(Nan::New("REL_MAX").ToLocalChecked(),
                Nan::New(REL_MAX));
    target->Set(Nan::New("REL_CNT").ToLocalChecked(),
                Nan::New(REL_CNT));
    target->Set(Nan::New("ABS_X").ToLocalChecked(),
                Nan::New(ABS_X));
    target->Set(Nan::New("ABS_Y").ToLocalChecked(),
                Nan::New(ABS_Y));
    target->Set(Nan::New("ABS_Z").ToLocalChecked(),
                Nan::New(ABS_Z));
    target->Set(Nan::New("ABS_RX").ToLocalChecked(),
                Nan::New(ABS_RX));
    target->Set(Nan::New("ABS_RY").ToLocalChecked(),
                Nan::New(ABS_RY));
    target->Set(Nan::New("ABS_RZ").ToLocalChecked(),
                Nan::New(ABS_RZ));
    target->Set(Nan::New("ABS_THROTTLE").ToLocalChecked(),
                Nan::New(ABS_THROTTLE));
    target->Set(Nan::New("ABS_RUDDER").ToLocalChecked(),
                Nan::New(ABS_RUDDER));
    target->Set(Nan::New("ABS_WHEEL").ToLocalChecked(),
                Nan::New(ABS_WHEEL));
    target->Set(Nan::New("ABS_GAS").ToLocalChecked(),
                Nan::New(ABS_GAS));
    target->Set(Nan::New("ABS_BRAKE").ToLocalChecked(),
                Nan::New(ABS_BRAKE));
    target->Set(Nan::New("ABS_HAT0X").ToLocalChecked(),
                Nan::New(ABS_HAT0X));
    target->Set(Nan::New("ABS_HAT0Y").ToLocalChecked(),
                Nan::New(ABS_HAT0Y));
    target->Set(Nan::New("ABS_HAT1X").ToLocalChecked(),
                Nan::New(ABS_HAT1X));
    target->Set(Nan::New("ABS_HAT1Y").ToLocalChecked(),
                Nan::New(ABS_HAT1Y));
    target->Set(Nan::New("ABS_HAT2X").ToLocalChecked(),
                Nan::New(ABS_HAT2X));
    target->Set(Nan::New("ABS_HAT2Y").ToLocalChecked(),
                Nan::New(ABS_HAT2Y));
    target->Set(Nan::New("ABS_HAT3X").ToLocalChecked(),
                Nan::New(ABS_HAT3X));
    target->Set(Nan::New("ABS_HAT3Y").ToLocalChecked(),
                Nan::New(ABS_HAT3Y));
    target->Set(Nan::New("ABS_PRESSURE").ToLocalChecked(),
                Nan::New(ABS_PRESSURE));
    target->Set(Nan::New("ABS_DISTANCE").ToLocalChecked(),
                Nan::New(ABS_DISTANCE));
    target->Set(Nan::New("ABS_TILT_X").ToLocalChecked(),
                Nan::New(ABS_TILT_X));
    target->Set(Nan::New("ABS_TILT_Y").ToLocalChecked(),
                Nan::New(ABS_TILT_Y));
    target->Set(Nan::New("ABS_TOOL_WIDTH").ToLocalChecked(),
                Nan::New(ABS_TOOL_WIDTH));
    target->Set(Nan::New("ABS_VOLUME").ToLocalChecked(),
                Nan::New(ABS_VOLUME));
    target->Set(Nan::New("ABS_MISC").ToLocalChecked(),
                Nan::New(ABS_MISC));
    target->Set(Nan::New("ABS_MT_SLOT").ToLocalChecked(),
                Nan::New(ABS_MT_SLOT));
    target->Set(Nan::New("ABS_MT_TOUCH_MAJOR").ToLocalChecked(),
                Nan::New(ABS_MT_TOUCH_MAJOR));
    target->Set(Nan::New("ABS_MT_TOUCH_MINOR").ToLocalChecked(),
                Nan::New(ABS_MT_TOUCH_MINOR));
    target->Set(Nan::New("ABS_MT_WIDTH_MAJOR").ToLocalChecked(),
                Nan::New(ABS_MT_WIDTH_MAJOR));
    target->Set(Nan::New("ABS_MT_WIDTH_MINOR").ToLocalChecked(),
                Nan::New(ABS_MT_WIDTH_MINOR));
    target->Set(Nan::New("ABS_MT_ORIENTATION").ToLocalChecked(),
                Nan::New(ABS_MT_ORIENTATION));
    target->Set(Nan::New("ABS_MT_POSITION_X").ToLocalChecked(),
                Nan::New(ABS_MT_POSITION_X));
    target->Set(Nan::New("ABS_MT_POSITION_Y").ToLocalChecked(),
                Nan::New(ABS_MT_POSITION_Y));
    target->Set(Nan::New("ABS_MT_TOOL_TYPE").ToLocalChecked(),
                Nan::New(ABS_MT_TOOL_TYPE));
    target->Set(Nan::New("ABS_MT_BLOB_ID").ToLocalChecked(),
                Nan::New(ABS_MT_BLOB_ID));
    target->Set(Nan::New("ABS_MT_TRACKING_ID").ToLocalChecked(),
                Nan::New(ABS_MT_TRACKING_ID));
    target->Set(Nan::New("ABS_MT_PRESSURE").ToLocalChecked(),
                Nan::New(ABS_MT_PRESSURE));
    target->Set(Nan::New("ABS_MT_DISTANCE").ToLocalChecked(),
                Nan::New(ABS_MT_DISTANCE));
    target->Set(Nan::New("ABS_MAX").ToLocalChecked(),
                Nan::New(ABS_MAX));
    target->Set(Nan::New("ABS_CNT").ToLocalChecked(),
                Nan::New(ABS_CNT));
    target->Set(Nan::New("SW_LID").ToLocalChecked(),
                Nan::New(SW_LID));
    target->Set(Nan::New("SW_TABLET_MODE").ToLocalChecked(),
                Nan::New(SW_TABLET_MODE));
    target->Set(Nan::New("SW_HEADPHONE_INSERT").ToLocalChecked(),
                Nan::New(SW_HEADPHONE_INSERT));
    target->Set(Nan::New("SW_RFKILL_ALL").ToLocalChecked(),
                Nan::New(SW_RFKILL_ALL));
    target->Set(Nan::New("SW_RADIO").ToLocalChecked(),
                Nan::New(SW_RADIO));
    target->Set(Nan::New("SW_MICROPHONE_INSERT").ToLocalChecked(),
                Nan::New(SW_MICROPHONE_INSERT));
    target->Set(Nan::New("SW_DOCK").ToLocalChecked(),
                Nan::New(SW_DOCK));
    target->Set(Nan::New("SW_LINEOUT_INSERT").ToLocalChecked(),
                Nan::New(SW_LINEOUT_INSERT));
    target->Set(Nan::New("SW_JACK_PHYSICAL_INSERT").ToLocalChecked(),
                Nan::New(SW_JACK_PHYSICAL_INSERT));
    target->Set(Nan::New("SW_VIDEOOUT_INSERT").ToLocalChecked(),
                Nan::New(SW_VIDEOOUT_INSERT));
    target->Set(Nan::New("SW_CAMERA_LENS_COVER").ToLocalChecked(),
                Nan::New(SW_CAMERA_LENS_COVER));
    target->Set(Nan::New("SW_KEYPAD_SLIDE").ToLocalChecked(),
                Nan::New(SW_KEYPAD_SLIDE));
    target->Set(Nan::New("SW_FRONT_PROXIMITY").ToLocalChecked(),
                Nan::New(SW_FRONT_PROXIMITY));
    target->Set(Nan::New("SW_ROTATE_LOCK").ToLocalChecked(),
                Nan::New(SW_ROTATE_LOCK));
    target->Set(Nan::New("SW_LINEIN_INSERT").ToLocalChecked(),
                Nan::New(SW_LINEIN_INSERT));
    target->Set(Nan::New("SW_MAX").ToLocalChecked(),
                Nan::New(SW_MAX));
    target->Set(Nan::New("SW_CNT").ToLocalChecked(),
                Nan::New(SW_CNT));
    target->Set(Nan::New("MSC_SERIAL").ToLocalChecked(),
                Nan::New(MSC_SERIAL));
    target->Set(Nan::New("MSC_PULSELED").ToLocalChecked(),
                Nan::New(MSC_PULSELED));
    target->Set(Nan::New("MSC_GESTURE").ToLocalChecked(),
                Nan::New(MSC_GESTURE));
    target->Set(Nan::New("MSC_RAW").ToLocalChecked(),
                Nan::New(MSC_RAW));
    target->Set(Nan::New("MSC_SCAN").ToLocalChecked(),
                Nan::New(MSC_SCAN));
    target->Set(Nan::New("MSC_MAX").ToLocalChecked(),
                Nan::New(MSC_MAX));
    target->Set(Nan::New("MSC_CNT").ToLocalChecked(),
                Nan::New(MSC_CNT));
    target->Set(Nan::New("LED_NUML").ToLocalChecked(),
                Nan::New(LED_NUML));
    target->Set(Nan::New("LED_CAPSL").ToLocalChecked(),
                Nan::New(LED_CAPSL));
    target->Set(Nan::New("LED_SCROLLL").ToLocalChecked(),
                Nan::New(LED_SCROLLL));
    target->Set(Nan::New("LED_COMPOSE").ToLocalChecked(),
                Nan::New(LED_COMPOSE));
    target->Set(Nan::New("LED_KANA").ToLocalChecked(),
                Nan::New(LED_KANA));
    target->Set(Nan::New("LED_SLEEP").ToLocalChecked(),
                Nan::New(LED_SLEEP));
    target->Set(Nan::New("LED_SUSPEND").ToLocalChecked(),
                Nan::New(LED_SUSPEND));
    target->Set(Nan::New("LED_MUTE").ToLocalChecked(),
                Nan::New(LED_MUTE));
    target->Set(Nan::New("LED_MISC").ToLocalChecked(),
                Nan::New(LED_MISC));
    target->Set(Nan::New("LED_MAIL").ToLocalChecked(),
                Nan::New(LED_MAIL));
    target->Set(Nan::New("LED_CHARGING").ToLocalChecked(),
                Nan::New(LED_CHARGING));
    target->Set(Nan::New("LED_MAX").ToLocalChecked(),
                Nan::New(LED_MAX));
    target->Set(Nan::New("LED_CNT").ToLocalChecked(),
                Nan::New(LED_CNT));
    target->Set(Nan::New("REP_DELAY").ToLocalChecked(),
                Nan::New(REP_DELAY));
    target->Set(Nan::New("REP_PERIOD").ToLocalChecked(),
                Nan::New(REP_PERIOD));
    target->Set(Nan::New("REP_MAX").ToLocalChecked(),
                Nan::New(REP_MAX));
    target->Set(Nan::New("REP_CNT").ToLocalChecked(),
                Nan::New(REP_CNT));
    target->Set(Nan::New("SND_CLICK").ToLocalChecked(),
                Nan::New(SND_CLICK));
    target->Set(Nan::New("SND_BELL").ToLocalChecked(),
                Nan::New(SND_BELL));
    target->Set(Nan::New("SND_TONE").ToLocalChecked(),
                Nan::New(SND_TONE));
    target->Set(Nan::New("SND_MAX").ToLocalChecked(),
                Nan::New(SND_MAX));
    target->Set(Nan::New("SND_CNT").ToLocalChecked(),
                Nan::New(SND_CNT));
    target->Set(Nan::New("ID_BUS").ToLocalChecked(),
                Nan::New(ID_BUS));
    target->Set(Nan::New("ID_VENDOR").ToLocalChecked(),
                Nan::New(ID_VENDOR));
    target->Set(Nan::New("ID_PRODUCT").ToLocalChecked(),
                Nan::New(ID_PRODUCT));
    target->Set(Nan::New("ID_VERSION").ToLocalChecked(),
                Nan::New(ID_VERSION));
    target->Set(Nan::New("BUS_PCI").ToLocalChecked(),
                Nan::New(BUS_PCI));
    target->Set(Nan::New("BUS_ISAPNP").ToLocalChecked(),
                Nan::New(BUS_ISAPNP));
    target->Set(Nan::New("BUS_USB").ToLocalChecked(),
                Nan::New(BUS_USB));
    target->Set(Nan::New("BUS_HIL").ToLocalChecked(),
                Nan::New(BUS_HIL));
    target->Set(Nan::New("BUS_BLUETOOTH").ToLocalChecked(),
                Nan::New(BUS_BLUETOOTH));
    target->Set(Nan::New("BUS_VIRTUAL").ToLocalChecked(),
                Nan::New(BUS_VIRTUAL));
    target->Set(Nan::New("BUS_ISA").ToLocalChecked(),
                Nan::New(BUS_ISA));
    target->Set(Nan::New("BUS_I8042").ToLocalChecked(),
                Nan::New(BUS_I8042));
    target->Set(Nan::New("BUS_XTKBD").ToLocalChecked(),
                Nan::New(BUS_XTKBD));
    target->Set(Nan::New("BUS_RS232").ToLocalChecked(),
                Nan::New(BUS_RS232));
    target->Set(Nan::New("BUS_GAMEPORT").ToLocalChecked(),
                Nan::New(BUS_GAMEPORT));
    target->Set(Nan::New("BUS_PARPORT").ToLocalChecked(),
                Nan::New(BUS_PARPORT));
    target->Set(Nan::New("BUS_AMIGA").ToLocalChecked(),
                Nan::New(BUS_AMIGA));
    target->Set(Nan::New("BUS_ADB").ToLocalChecked(),
                Nan::New(BUS_ADB));
    target->Set(Nan::New("BUS_I2C").ToLocalChecked(),
                Nan::New(BUS_I2C));
    target->Set(Nan::New("BUS_HOST").ToLocalChecked(),
                Nan::New(BUS_HOST));
    target->Set(Nan::New("BUS_GSC").ToLocalChecked(),
                Nan::New(BUS_GSC));
    target->Set(Nan::New("BUS_ATARI").ToLocalChecked(),
                Nan::New(BUS_ATARI));
    target->Set(Nan::New("BUS_SPI").ToLocalChecked(),
                Nan::New(BUS_SPI));
    target->Set(Nan::New("MT_TOOL_FINGER").ToLocalChecked(),
                Nan::New(MT_TOOL_FINGER));
    target->Set(Nan::New("MT_TOOL_PEN").ToLocalChecked(),
                Nan::New(MT_TOOL_PEN));
    target->Set(Nan::New("MT_TOOL_MAX").ToLocalChecked(),
                Nan::New(MT_TOOL_MAX));
    target->Set(Nan::New("FF_STATUS_STOPPED").ToLocalChecked(),
                Nan::New(FF_STATUS_STOPPED));
    target->Set(Nan::New("FF_STATUS_PLAYING").ToLocalChecked(),
                Nan::New(FF_STATUS_PLAYING));
    target->Set(Nan::New("FF_STATUS_MAX").ToLocalChecked(),
                Nan::New(FF_STATUS_MAX));
    target->Set(Nan::New("FF_RUMBLE").ToLocalChecked(),
                Nan::New(FF_RUMBLE));
    target->Set(Nan::New("FF_PERIODIC").ToLocalChecked(),
                Nan::New(FF_PERIODIC));
    target->Set(Nan::New("FF_CONSTANT").ToLocalChecked(),
                Nan::New(FF_CONSTANT));
    target->Set(Nan::New("FF_SPRING").ToLocalChecked(),
                Nan::New(FF_SPRING));
    target->Set(Nan::New("FF_FRICTION").ToLocalChecked(),
                Nan::New(FF_FRICTION));
    target->Set(Nan::New("FF_DAMPER").ToLocalChecked(),
                Nan::New(FF_DAMPER));
    target->Set(Nan::New("FF_INERTIA").ToLocalChecked(),
                Nan::New(FF_INERTIA));
    target->Set(Nan::New("FF_RAMP").ToLocalChecked(),
                Nan::New(FF_RAMP));
    target->Set(Nan::New("FF_EFFECT_MIN").ToLocalChecked(),
                Nan::New(FF_EFFECT_MIN));
    target->Set(Nan::New("FF_EFFECT_MAX").ToLocalChecked(),
                Nan::New(FF_EFFECT_MAX));
    target->Set(Nan::New("FF_SQUARE").ToLocalChecked(),
                Nan::New(FF_SQUARE));
    target->Set(Nan::New("FF_TRIANGLE").ToLocalChecked(),
                Nan::New(FF_TRIANGLE));
    target->Set(Nan::New("FF_SINE").ToLocalChecked(),
                Nan::New(FF_SINE));
    target->Set(Nan::New("FF_SAW_UP").ToLocalChecked(),
                Nan::New(FF_SAW_UP));
    target->Set(Nan::New("FF_SAW_DOWN").ToLocalChecked(),
                Nan::New(FF_SAW_DOWN));
    target->Set(Nan::New("FF_CUSTOM").ToLocalChecked(),
                Nan::New(FF_CUSTOM));
    target->Set(Nan::New("FF_WAVEFORM_MIN").ToLocalChecked(),
                Nan::New(FF_WAVEFORM_MIN));
    target->Set(Nan::New("FF_WAVEFORM_MAX").ToLocalChecked(),
                Nan::New(FF_WAVEFORM_MAX));
    target->Set(Nan::New("FF_GAIN").ToLocalChecked(),
                Nan::New(FF_GAIN));
    target->Set(Nan::New("FF_AUTOCENTER").ToLocalChecked(),
                Nan::New(FF_AUTOCENTER));
    target->Set(Nan::New("FF_MAX").ToLocalChecked(),
                Nan::New(FF_MAX));
    target->Set(Nan::New("FF_CNT").ToLocalChecked(),
                Nan::New(FF_CNT));

    /* uinput.h */
    target->Set(Nan::New("UI_DEV_CREATE").ToLocalChecked(),
                Nan::New(UI_DEV_CREATE));
    target->Set(Nan::New("UI_DEV_DESTROY").ToLocalChecked(),
                Nan::New(UI_DEV_DESTROY));
    target->Set(Nan::New("UI_SET_EVBIT").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_SET_EVBIT)));
    target->Set(Nan::New("UI_SET_KEYBIT").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_SET_KEYBIT)));
    target->Set(Nan::New("UI_SET_RELBIT").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_SET_RELBIT)));
    target->Set(Nan::New("UI_SET_ABSBIT").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_SET_ABSBIT)));
    target->Set(Nan::New("UI_SET_MSCBIT").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_SET_MSCBIT)));
    target->Set(Nan::New("UI_SET_LEDBIT").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_SET_LEDBIT)));
    target->Set(Nan::New("UI_SET_SNDBIT").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_SET_SNDBIT)));
    target->Set(Nan::New("UI_SET_FFBIT").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_SET_FFBIT)));
    target->Set(Nan::New("UI_SET_PHYS").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_SET_PHYS)));
    target->Set(Nan::New("UI_SET_SWBIT").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_SET_SWBIT)));
    target->Set(Nan::New("UI_SET_PROPBIT").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_SET_PROPBIT)));
    target->Set(Nan::New("UI_BEGIN_FF_UPLOAD").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_BEGIN_FF_UPLOAD)));
    target->Set(Nan::New("UI_END_FF_UPLOAD").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_END_FF_UPLOAD)));
    target->Set(Nan::New("UI_BEGIN_FF_ERASE").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_BEGIN_FF_ERASE)));
    target->Set(Nan::New("UI_END_FF_ERASE").ToLocalChecked(),
                Nan::New(static_cast<uint32_t>(UI_END_FF_ERASE)));
    target->Set(Nan::New("EV_UINPUT").ToLocalChecked(),
                Nan::New(EV_UINPUT));
    target->Set(Nan::New("UI_FF_UPLOAD").ToLocalChecked(),
                Nan::New(UI_FF_UPLOAD));
    target->Set(Nan::New("UI_FF_ERASE").ToLocalChecked(),
                Nan::New(UI_FF_ERASE));
    target->Set(Nan::New("UINPUT_MAX_NAME_SIZE").ToLocalChecked(),
                Nan::New(UINPUT_MAX_NAME_SIZE));


    target->Set(Nan::New("input_event").ToLocalChecked(),
                Nan::New<FunctionTemplate>(InputEvent)->GetFunction());
}
}

NODE_MODULE(uinput, Initialize)
